# Generated by Django 4.2.20 on 2025-04-06 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KefirType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип кефира')),
            ],
        ),
        migrations.CreateModel(
            name='Kefir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=20, unique=True, verbose_name='Артикул')),
                ('brand', models.CharField(max_length=100, verbose_name='Бренд')),
                ('fat_content', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Жирность (%)')),
                ('volume', models.PositiveIntegerField(verbose_name='Объем (мл)')),
                ('is_bio', models.BooleanField(default=False, verbose_name='Биокефир')),
                ('shelf_life', models.PositiveIntegerField(verbose_name='Срок годности (дни)')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='Цвет')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
                ('kefir_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.kefirtype', verbose_name='Тип кефира')),
            ],
        ),
    ]
