# Generated by Django 4.2.20 on 2025-04-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kefir',
            name='volume',
            field=models.PositiveIntegerField(default=500, verbose_name='Объем (мл)'),
        ),
    ]
