# Generated by Django 4.2.20 on 2025-04-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_kefir_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kefir',
            name='is_bio',
        ),
        migrations.AddField(
            model_name='kefir',
            name='is_lactose_free',
            field=models.BooleanField(default=False, verbose_name='Безлактозный'),
        ),
    ]
