# Generated by Django 4.2.20 on 2025-04-06 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_kefir_is_bio_kefir_is_lactose_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kefir',
            name='color',
        ),
    ]
