# Generated by Django 4.2.20 on 2025-04-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_kefir_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='kefir',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='kefir_images/', verbose_name='Изображение'),
        ),
    ]
