# Generated by Django 4.2.20 on 2025-04-06 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_kefir_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='KefirBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Вкусвилл', max_length=100, verbose_name='Бренд кефира')),
            ],
        ),
        migrations.AddField(
            model_name='kefir',
            name='extra_flavor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дополнительный вкус'),
        ),
        migrations.AlterField(
            model_name='kefir',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.kefirbrand', verbose_name='Бренд'),
        ),
    ]
