# Generated by Django 4.2.20 on 2025-04-27 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_kefirbrand_kefir_extra_flavor_alter_kefir_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kefir',
            name='fat_content',
            field=models.DecimalField(decimal_places=1, default=2.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Жирность (%)'),
        ),
        migrations.AlterField(
            model_name='kefir',
            name='price',
            field=models.DecimalField(decimal_places=2, default=250, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='kefir',
            name='shelf_life',
            field=models.PositiveIntegerField(default=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Срок годности (дни)'),
        ),
        migrations.AlterField(
            model_name='kefir',
            name='volume',
            field=models.PositiveIntegerField(default=500, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Объем (мл)'),
        ),
    ]
