# Generated by Django 4.2.20 on 2025-04-27 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_kefir_fat_content_alter_kefir_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kefir',
            name='large_wholesale_min_qty',
            field=models.PositiveIntegerField(default=50, verbose_name='Мин. кол-во для крупного опта'),
        ),
        migrations.AddField(
            model_name='kefir',
            name='large_wholesale_price',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Крупнооптовая цена'),
        ),
        migrations.AddField(
            model_name='kefir',
            name='small_wholesale_min_qty',
            field=models.PositiveIntegerField(default=10, verbose_name='Мин. кол-во для мелкого опта'),
        ),
        migrations.AddField(
            model_name='kefir',
            name='small_wholesale_price',
            field=models.DecimalField(decimal_places=2, default=220, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Мелкооптовая цена'),
        ),
        migrations.AlterField(
            model_name='kefir',
            name='price',
            field=models.DecimalField(decimal_places=2, default=250, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Розничная цена'),
        ),
    ]
